org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=alchemylib
mod_name=AlchemyLib
mod_license=LGPLv2.1
mod_version=
mod_group_id=
mod_authors=DarkArcana
mod_description=AlchemyLib is a library mod for ChemLib addon mods such as Alchemistry and Techemistry. Anyone can use AlchemyLib to help bootstrap their mod development. Everything you need is in the api package.

# Minecraft
minecraftVersion=1.21.1

# NeoForge
neoVersion=21.1.219
neoforgeVersionRange=[21,22)

# Parchment
parchmentMinecraftVersion=1.21.1
parchmentMappingsVersion=2024.11.17

# Mod
modVersion=1.0.30

chemlib_version=2.0.17