modLoader="javafml"
loaderVersion="[0,)"
license="LGPLv2.1"
issueTrackerURL="https://github.com/TonimatasDEV/AlchemyLib/issues"

[[mods]]
modId="alchemylib"
version="${modVersion}"
displayName="AlchemyLib"
logoFile="alchemylib-logo.png"
authors="DarkArcana - Creator | TonimatasDEV - Port"
description='''
AlchemyLib is a library mod for ChemLib addon mods such as Alchemistry and Techemistry. Anyone can use AlchemyLib to help bootstrap their mod development. Everything you need is in the api package.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.alchemylib]]
modId="neoforge"
required=true
versionRange="${neoforgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.alchemylib]]
modId="minecraft"
required=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"

[[dependencies.alchemylib]]
modId="chemlib"
required=true
versionRange="${chemlibVersionRange}"
ordering="NONE"
side="BOTH"