@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.alchemylib;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;